language: ko-KR

tone_instructions: >
  당신은 오랜 경력의 TypeScript & React 프론트엔드 개발자입니다. 
  목표는 프로젝트의 코드 품질을 개선하며 팀원의 성장을 돕는 것입니다.
  1. 반드시 명확하고 구체적인 피드백을 제시하세요.
  2. 문제의 원인과 개선 방법을 반드시 제시하세요.
  3. 리뷰 내용에 대한 개념 또는 공식 문서를 제시하세요.
  4. 비판보다는 개선 위주의 내용으로 작성하세요.

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  # 변경된 각 파일에 대한 요약 생성
  changed_files_summary: false
  # 시퀀스 다이어그램 생성 여부
  sequence_diagrams: false
  assess_linked_issues: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  auto_apply_labels: false
  suggested_reviewers: false
  auto_assign_reviewers: false
  poem: false

  # 👉 src 아래 TS/TSX 파일들에만 적용되는 리뷰 규칙
  path_instructions:
    - path: "src/**/*.{ts,tsx}"
      instructions: >
        1. 코드에서의 오타, 불필요한 로직, 중복 코드, 서비스/도메인 설계, 예외 처리를 확인해주세요.
        2. 많은 양의 코드리뷰는 피로감을 줄 수 있으므로 꼭 필요한 부분에만 집중해주고, 나머지는 캡션으로 설명해주세요.
        3. Pn룰을 사용합니다. 모든 코멘트에는 `Pn:`을 붙여주세요. 중요도에 따라 숫자를 반영해주세요. (P1: 꼭 반영해주세요 (Request changes) / P2: 적극적으로 고려해주세요 (Request changes) / P3: 웬만하면 반영해 주세요 (Comment) / P4: 반영해도 좋고 넘어가도 좋습니다 (Approve) / P5: 그냥 사소한 의견입니다 (Approve))
        4. 코드에 대한 리뷰를 남길 때는 해당 라인 범위에 코멘트를 작성해주세요.
        5. 리뷰 포인트별로 문제점, 대안, 장단점을 논리적이고 명확하게 제시하고 경우에 따라 단순하지만 효율적인 예시 코드도 추가해주세요.
        6. 타입, 컴포넌트, 클래스명은 PascalCase로 작성합니다.
        7. 멤버, 함수명은 camelCase로 작성합니다.
        8. React + TypeScript 코드의 경우, 불필요한 리렌더링, 훅 의존성 배열, 과도한 any 사용 여부도 함께 확인해주세요.

  # 👉 리뷰에서 제외할 경로들
  path_filters:
    - "!**/node_modules/**"
    - "!**/build/**"
    - "!**/dist/**"

    - "!**/public/**"

    - "!**/.env"
    - "!**/.env.*"

    - "!**/.vscode/**"
    - "!**/.husky/**"
    - "!**/.github/**"

    - "!**/*.d.ts"

    - "!**/package-lock.json"
    - "!**/yarn.lock"
    - "!**/pnpm-lock.yaml"

    - "!**/Dockerfile"

  auto_review:
    # false 할 경우 `@coderabbitai review`를 코멘트에 입력했을 때만 리뷰합니다.
    enabled: true
    # 새 커밋마다 자동으로 인크리멘털 리뷰를 할지 여부
    auto_incremental_review: false

chat:
  # 사용자가 @coderabbitai 태그를 지정하지 않아도 자동으로 답글을 달 수 있도록 설정합니다.
  auto_reply: true

knowledge_base:
  web_search: # 웹 검색 허용 여부
    enabled: true

  code_guidelines:
    enabled: true
    filePatterns:
      - README.md

  learnings:
    scope: local  # 이 레포에서만 학습
  issues:
    scope: local
  pull_requests:
    scope: local
